note/urls.py
from django.urls import path 
from . import views 
urlpatterns = [
    path('', views.home, name='note-home'),
    path('<int:pk>/', views.NoteDetailView.as_view(), name='note-detail'),
    path('create/', views.createNote, name='note-create'), 
    path('<int:pk>/edit/', views.editNote.as_view(), name='note-edit')
]

noteTaking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('note.urls'))
]

note/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse_lazy
# Create your models here.
class note(models.Model):
    title = models.CharField(max_length=100) 
    content = models.TextField(blank=True) 
    created_date = models.DateTimeField(timezone.now()) 
    modified_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title 

note/forms.py
from .models import note
from django import forms


class createNoteForm(forms.ModelForm):
    class Meta:
        model = note
        fields = ['title', 'content']

class editNoteForm(forms.Form):
    class Meta:
        model = note
        fields = ['title', 'content']

note/views.py
from django.shortcuts import render, redirect
from .models import note
from django.views.generic import DetailView, UpdateView
from .forms import createNoteForm, editNoteForm
from django.urls import reverse_lazy
from django.utils import timezone
import datetime

# Create your views here.
def home(request): 
    return render(request, 'note/index.html', {'notes': note.objects.all()})


class NoteDetailView(DetailView):
    model = note 
    
def createNote(request):
    if request.method == 'POST': 
        form = createNoteForm(request.POST) 

        if form.is_valid():  
            title = form.cleaned_data.get('title')
            data = form.save(commit=False) 
            data.created_date = timezone.localtime()
            data.save()
            return redirect('note-home')
    else: 
        form = createNoteForm() 
    return render(request, 'note/note_form.html', {'form': form})
    

class editNote(UpdateView):
    model = note 
    fields = ['title', 'content']
    template_name_suffix = '_update_form'
    
    def get_success_url(self):
        noteId = self.kwargs['pk']
        return reverse_lazy('note-detail', kwargs={'pk': noteId})
    

note/templates/note/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Note keeper</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'note/style.css' %}"
    />
  </head>
  <body>
    <span style="text-align: center;"><h1>Noter</h1></span>
    {% block content %} {% endblock %}
  </body>
</html>

note/templates/note/index.html
{% extends 'note/base.html' %}{% load markdown_deux_tags %} {% block content %}
<div class="container">
  {% for note in notes%}
  <h3>
    <a href="{% url 'note-detail' note.pk %}">{{ note.title }}</a>
  </h3>

  {% endfor %}
  <button><a href="{% url 'note-create' %}">Create note +</a></button>
</div>
{% endblock content %}

note/templates/note/note_detail.html
{% load static %} {% load markdown_deux_tags %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Noter</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'note/note_detail_style.css' %}"
    />
  </head>
  <body>
    <!-- Sidebar -->
    <div class="sidebar">
      <div class='sidebar-actions-provided'>
        <button>
          <a href="{% url 'note-home' %}">
            <img src="{% static 'note/homeLogo.png' %}" id='home'></img> 
          </a>
        </button>
        <button onclick="btnOnClick()">       
            <img src="{% static 'note/outline.png' %}" id='file'></img>
        </button>
        <button>
          <a href="{% url 'note-create' %}">
            <img src="{% static 'note/newFileLogo.png' %}" id='create'></img> 
          </a>
        </button>
        <button>
          <a href="{% url 'note-edit' note.pk %}">
            <img src="{% static 'note/editLogo.png' %}" id='edit'></img> 
          </a>
        </button>
        
      </div>
      <div class="sidebar-list-outline">
      </div>
      <div class="sidebar-list-file">
        {% for file in files %}
        <div class='sidebar-link-container'><a href="{% url 'note-detail' file.pk %}" class='h1Link'>{{ file }}</a></div>
        {% endfor %}
      </div>
    </div>



    <!-- Content -->
    <div class="content">
      <div>
        <h1 style="display: inline;">{{ object.title }}</h1>
      </div>
      
      {{ object.content|markdown }}

    </div>

    <script src="{% static 'note/note_detail_js.js' %}">
      
    </script>
  </body>
</html>

note/templates/note/note_form.html
{% load crispy_forms_tags %}
<style>
  #id_title {
      width: 100%;
      border: 0px;
      border-bottom: 2px solid lightgrey;
  }
  #id_title:focus {
      outline: none !important;
      border-bottom: 2px solid grey;
  }
  textarea {
    outline: none !important;   
    resize: none;
    width: 100%;
    height: 70%;
    overflow-y: scroll;
  }
  #save-btn {
    font-size: 50px;
    width: 100px;
    float: right;
  }
</style>
<form method="POST">
  {% csrf_token %} {{ form|crispy }}
  <div class="save-btn-container">
    <input type="submit" value="Save" id="save-btn" />
  </div>
</form>

note/templates/note/note_update_form.html
{% load crispy_forms_tags %}
<style>
    * {
        font-size: 18px;
    }
  #id_title {
    width: 100%;
    border: 0px;
    border-bottom: 2px solid lightgrey;
  }
  #id_title:focus {
    outline: none !important;
    border-bottom: 2px solid grey;
  }
  textarea {
    outline: none !important;
    resize: none;
    width: 100%;
    height: 70%;
    overflow-y: scroll;
  }
  #save-btn {
    font-size: 50px;
    width: 100px;
    float: right;
  }
</style>
{% block content %}
<form method="post">
  {% csrf_token %} {{ form|crispy }}
  <input type="submit" value="Update" id="save-btn" />
</form>

{% endblock content %}